name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget tar bzip2 python3 python3-pip
      
      - name: Install devkitPro pacman
        run: |
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
      
      - name: Install devkitARM (for GBA)
        run: |
          sudo dkp-pacman -S --noconfirm gba-dev

      - name: Set up Gameboy Advance toolchain
        run: cd build && ./set-gameboy-advance-toolchain.sh

      - name: Build project
        run: ./build.sh
