name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget tar bzip2 python3 python3-pip cmake
      
      - name: Install devkitPro pacman and setup devkitpro
        run: |
         
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -Sy
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/devkitARM
          export DEVKITPPC=/opt/devkitpro/devkitPPC

      - name: Install devkitARM (for GBA)
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/devkitARM
          export DEVKITPPC=/opt/devkitpro/devkitPPC
          sudo dkp-pacman -S --noconfirm gba-dev

      - name: Set up Gameboy Advance toolchain
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/devkitARM
          export DEVKITPPC=/opt/devkitpro/devkitPPC
          cd build && ./set-gameboy-advance-toolchain.sh

      - name: Build project
        run: ./build.sh
