name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix git safe directory
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          git config --global --add safe.directory /__w/skyland-beta/skyland-beta

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget tar bzip2 python3 python3-pip cmake
          pip3 install pillow
          
      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            build/CMakeCache.txt
            build/CMakeFiles
          key: build-${{ runner.os }}-${{ hashFiles('source/**', 'scripts/**', 'build/CMakeLists.txt', 'build/*.sh') }}
          restore-keys: |
            build-${{ runner.os }}-

      - name: Build project
        run: |
          cd build
          if [ ! -f CMakeCache.txt ]; then
            ./set-gameboy-advance-toolchain.sh
          fi
          chmod +x build.sh && ./build.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Skyland-gba
          path: build/Skyland.gba
